version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dota-clarity"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-144vmo637n44"
s3_prefix = "dota-clarity"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"aws\" BucketName=\"dota-clarity\""

