AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dota-clarity

  Sample SAM Template for dota-clarity

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  DotaClarityCreateProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dota_clarity/
      Handler: create_profile.lambda_handler
      Runtime: python3.8
      Events:
        CreateProfile:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profiles
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DotaClarityApi:
    Description: "API Gateway endpoint URL for Prod stage for Dota Clarity Functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profiles/"
  DotaClarityCreateProfileFunction:
    Description: "Dota Clarity Create Profile Lambda Function ARN"
    Value: !GetAtt DotaClarityCreateProfileFunction.Arn
  DotaClarityCreateProfileFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Create Profile function"
    Value: !GetAtt DotaClarityCreateProfileFunction.Arn
