AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dota-clarity

  SAM Template for dota-clarity

Globals:
  Function:
    Timeout: 10 

Parameters:
  Environment:
    Type: String
    Default: aws
    Description: (Required) The name of the environment you are working in - aws or local
    AllowedValues:
      - local
      - aws

Resources:
  ProfilesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${AWS::StackName}-profiles-table
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  MatchesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${AWS::StackName}-matches-table
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: match_id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: "match_id"
          KeyType: "RANGE"
  CreateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-profile
      CodeUri: functions/profiles/create_profile/
      Handler: create_profile.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: !Ref ProfilesTable
          TABLE_ARN: !GetAtt ProfilesTable.Arn
      Events:
        CreateProfileAPI:
          Type: Api
          Properties:
            Path: /profiles/
            Method: POST
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get-profile
      CodeUri: functions/profiles/get_profile/
      Handler: get_profile.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: !Ref ProfilesTable
          TABLE_ARN: !GetAtt ProfilesTable.Arn
      Events:
        GetProfileAPI:
          Type: Api
          Properties:
            Path: /profiles/{id}
            Method: GET
  CreateFavouriteMatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-favourite-match
      CodeUri: functions/matches/favourites/create_match/
      Handler: create_match.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MatchesTable
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: !Ref MatchesTable
          TABLE_ARN: !GetAtt MatchesTable.Arn
      Events:
        CreateMatchAPI:
          Type: Api
          Properties:
            Path: /matches/favourites/{id}
            Method: POST
  GetFavouriteMatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get-favourite-match
      CodeUri: functions/matches/favourites/get_match/
      Handler: get_match.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MatchesTable
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: !Ref MatchesTable
          TABLE_ARN: !GetAtt MatchesTable.Arn
      Events:
        CreateMatchAPI:
          Type: Api
          Properties:
            Path: /matches/favourites/{id}/{match_id}
            Method: GET
  GetFavouriteMatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get-favourite-matches
      CodeUri: functions/matches/favourites/get_matches/
      Handler: get_matches.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MatchesTable
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: !Ref MatchesTable
          TABLE_ARN: !GetAtt MatchesTable.Arn
      Events:
        CreateMatchAPI:
          Type: Api
          Properties:
            Path: /matches/favourites/{id}/
            Method: GET
  GetMatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get-match
      CodeUri: functions/matches/get_match/
      Handler: get_match.lambda_handler
      Runtime: python3.8
      Events:
        CreateMatchAPI:
          Type: Api
          Properties:
            Path: /matches/{match_id}/
            Method: GET
  GetAllMatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get-all-matches
      CodeUri: functions/matches/get_all_matches/
      Handler: get_all_matches.lambda_handler
      Runtime: python3.8
      Events:
        CreateMatchAPI:
          Type: Api
          Properties:
            Path: /matches/{steam_id}/
            Method: GET
  DotaClarityS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: landing.html
        ErrorDocument: error.html
  DotaClarityS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: Dota Clarity Frontend Bucket Policy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DotaClarityS3Bucket
                - /*
      Bucket: !Ref DotaClarityS3Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DotaClarityApi:
    Description: "API Gateway endpoint URL for Prod stage for Dota Clarity Functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profiles/"
  CreateProfileFunction:
    Description: "Dota Clarity Create Profile Lambda Function ARN"
    Value: !GetAtt CreateProfileFunction.Arn
  CreateProfileFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Create Profile function"
    Value: !GetAtt CreateProfileFunction.Arn
  GetProfileFunction:
    Description: "Dota Clarity Get Profile Lambda Function ARN"
    Value: !GetAtt GetProfileFunction.Arn
  GetProfileFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Get Profile function"
    Value: !GetAtt GetProfileFunction.Arn
  CreateFavouriteMatchFunction:
    Description: "Dota Clarity Create Favourite Match Lambda Function ARN"
    Value: !GetAtt CreateFavouriteMatchFunction.Arn
  CreateFavouriteMatchFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Create Favourite Match function"
    Value: !GetAtt CreateFavouriteMatchFunction.Arn
  GetFavouriteMatchFunction:
    Description: "Dota Clarity Get Favourite Match Lambda Function ARN"
    Value: !GetAtt GetFavouriteMatchFunction.Arn
  GetFavouriteMatchFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Get Favourite Match function"
    Value: !GetAtt GetFavouriteMatchFunction.Arn
  GetFavouriteMatchesFunction:
    Description: "Dota Clarity Get Favourite Matches Lambda Function ARN"
    Value: !GetAtt GetFavouriteMatchesFunction.Arn
  GetFavouriteMatchesFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Get Favourite Matches function"
    Value: !GetAtt GetFavouriteMatchesFunction.Arn
  GetMatchFunction:
    Description: "Dota Clarity Get Match Lambda Function ARN"
    Value: !GetAtt GetMatchFunction.Arn
  GetMatchFunctionIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Get Match function"
    Value: !GetAtt GetMatchFunction.Arn
  GetAllMatchesFunction:
    Description: "Dota Clarity Get All Matches Lambda Function ARN"
    Value: !GetAtt GetAllMatches.Arn
  GetAllMatchesIamRole:
    Description: "Implicit IAM Role created for Dota Clarity Get All Matches function"
    Value: !GetAtt GetAllMatches.Arn
  WebsiteURL:
    Value: !GetAtt 
      - DotaClarityS3Bucket
      - WebsiteURL
    Description: URL for Dota Clarity website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - DotaClarityS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
